// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqiGCdNtznT3HTj9oL9ElL676o2UHkDYo',
    appId: '1:851673056395:web:25769317f64aed9ba5008e',
    messagingSenderId: '851673056395',
    projectId: 'carbon-74f15',
    authDomain: 'carbon-74f15.firebaseapp.com',
    storageBucket: 'carbon-74f15.appspot.com',
    measurementId: 'G-0BF05K2Y6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_zmM-wMN4cmfbBwkmyaOiA3Qdu3SjZjE',
    appId: '1:851673056395:android:9838311ec233c9c0a5008e',
    messagingSenderId: '851673056395',
    projectId: 'carbon-74f15',
    storageBucket: 'carbon-74f15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhi-JOidReQz7nd3hea7hA3DxNxP3gD3E',
    appId: '1:851673056395:ios:6611c70bc5c79b47a5008e',
    messagingSenderId: '851673056395',
    projectId: 'carbon-74f15',
    storageBucket: 'carbon-74f15.appspot.com',
    iosClientId: '851673056395-hjpp6pjc1bopdjki1cat3bto570q844q.apps.googleusercontent.com',
    iosBundleId: 'com.example.machinesBuiltByMachines',
  );
}
